version: '3'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: db_mongo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_CUSTOM_USERNAME: user
      MONGO_CUSTOM_PASSWORD: userpass
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongodata:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: userpass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpass
    links:
      - mongo
    networks:
      - mongo-compose-network

volumes:
  mongodata:

networks: 
  mongo-compose-network:
    driver: bridge